import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Minimalist_theme - A VSCode Theme</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-color3 h-min-screen text-center pt-10 pb-10">
        <h1 className="text-color1 text-5xl font-bold mt-20 mb-36">
            Minimalist_theme
        </h1>

        <p className='text-color2 text-2xl font-semibold mb-10'>
          A simple dark theme for Visual Studio Code inspired by Monokai Pro theme.
        </p>

        <a className="block ml-auto mr-auto rounded" data-bs-toggle="tooltip" data-bs-placement="bottom" title="GitHub Link" target="_blank" rel="noopener noreferrer" href="https://github.com/sayantikag98/minimalist-theme.git"><Image src="/GitHub-Mark/GitHub-Mark/PNG/GitHub-Mark-Light-120px-plus.png" alt="GitHub Logo" height={60} width={60} /></a>

        <h3 className='text-color2 text-xl mt-10 mb-24'>Available on <a className="font-bold text-color5 text-2xl hover:underline hover:underline-offset-1 hover:decoration-color1 hover:decoration-double p-0.5 rounded-lg" target="_blank" rel="noopener noreferrer" href="https://marketplace.visualstudio.com/items?itemName=sayantikag98.minimalist-theme">Visual Studio Code Marketplace</a>.</h3>

        <Image className="rounded-lg" src="/images/Minimalist_theme.png" alt="Theme image" height={450} width={900}/>

        <div className="mt-36 mb-10"><h4 className='text-color2 border-4 border-double border-color1 w-fit ml-auto mr-auto p-2 rounded-lg'>Designed by Sayantika Ghosh</h4></div>
       
      </main>
    </div>
  )
}
